### ISSUE TITLE
请问有没有固定配色的方法或者选项？

### ISSUE THREAD

**Issue by xavierskip** [prinsss/blog-friend-circle#4]
观察到此工具会根据系统的日间、夜间模式进行颜色适配，但是对于一些并没有进行这种适配的页面来说，在夜间模式的系统下，此工具页面的字体是浅色，因为页面并没有做暗色系统的适配同样也是浅色，导致难以阅读。

请问有没有方法或者选项来固定配色？

本来以为可以在 `data-style="color-scheme: light;"` 来固定使用浅色配色，结果发现除了 firefox ，其他浏览器均不兼容

![image](https://github.com/user-attachments/assets/804886d0-8aa5-48e8-bb1c-80be3427bbfb)
[https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7)

**Comment by prinsss** [comment]
Hi，感谢你的反馈！

我刚刚更新了代码，现在可以通过 `data-theme` 属性指定浅色模式/深色模式了。

```jsx
<script
  // 设置内容的颜色方案。可用选项: "auto", "light", "dark".
  data-theme="auto"
  src="https://circle.example.workers.dev/app.js"
  async
></script>
```

如有其他问题，欢迎继续反馈。:)

**Comment by xavierskip** [comment]
好好好！

不过在这个阶段里我顺便给自己的博客适配了暗配色🤣
